### ISSUE TITLE
Allow for daemons to have optional graceful shutdown 

### ISSUE THREAD

**Issue by Dev-Dominic** [PalisadoesFoundation/pattoo-shared#109]
Currently daemons don't have the ability to gracefully shutdown which means they don't check that the current process has complete prior to shutting down or restarting. This could pose a problem in terms of data ingerity (i.e data loss or corruption). 

Association Issues:
PalisadoesFoundation/pattoo#231

**Comment by gill876** [comment]
https://github.com/PalisadoesFoundation/pattoo-shared/blob/64d14de48e4a32f16cedce2d1e6f3269ac50824d/pattoo_shared/daemon.py#L180

For a safe shutdown, a new function would have to be created like this stop function. Except, how would the function know if the currently running process still has data to be transferred? Would it have to check the ingester cache to see if data is remaining? Which particular process or file(s) should it look for before terminating the daemon?

**Comment by palisadoes** [comment]
> https://github.com/PalisadoesFoundation/pattoo-shared/blob/64d14de48e4a32f16cedce2d1e6f3269ac50824d/pattoo_shared/daemon.py#L180
> 
> For a safe shutdown, a new function would have to be created like this stop function. Except, how would the function know if the currently running process still has data to be transferred? Would it have to check the ingester cache to see if data is remaining? Which particular process or file(s) should it look for before terminating the daemon?

1. pattoo.ingest.files.process_cache() creates a lock file when ingesting data. One solution could be to use the presence of the file as a trigger. Test by creating a fake lock file.
1. You an make this generic by testing for lock files named after the agent as the trigger. You may have noticed that all daemons are given agent names too.
